<section class="span9 first">
<?php
    include_once 'site/view/pages/v_banner.php'; 
?>
    <div id="right">
<!-- ESI END DUMMY COMMENT [] -->
<p class="caption" style="text-align: justify;">THÔNG TIN GIỚI THIỆU CỬA HÀNG BÁN SÁCH MINH VŨ</p>
<p style="text-align: justify;"><strong><img style="float: right;" src="http://www.fahasa.com/media/wysiwyg/fahasa.jpg" alt="Fahasa" width="271" height="461" /></strong><strong></strong></p>
<p style="text-align: justify;"><strong> </strong><strong>Nguồn nh&acirc;n lực</strong></p>
<p style="text-align: justify;">Để x&acirc;y dựng Thương hiệu mạnh, một trong những định hướng quan trọng h&agrave;ng đầu của FAHASA l&agrave; chiến lược ph&aacute;t triển nguồn nh&acirc;n lực - mấu chốt của mọi sự th&agrave;nh c&ocirc;ng.</p>
<p style="text-align: justify;">FAHASA c&oacute; hơn 2.200 CB-CNV, tr&igrave;nh độ chuy&ecirc;n m&ocirc;n giỏi, nhiệt t&igrave;nh, năng động, chuy&ecirc;n nghiệp. Lực lượng quản l&yacute; FAHASA c&oacute; th&acirc;m ni&ecirc;n c&ocirc;ng t&aacute;c, giỏi nghiệp vụ nhiều kinh nghiệm, c&oacute; khả năng quản l&yacute; tốt v&agrave; điều h&agrave;nh đơn vị hoạt động hiệu quả.</p>
<p style="text-align: justify;">Kết hợp tuyển dụng nguồn nh&acirc;n lực đầu v&agrave;o c&oacute; chất lượng v&agrave; kế hoạch bồi dưỡng kiến thức, r&egrave;n luyện bổ sung c&aacute;c kỹ năng v&agrave; chuẩn bị đội ngũ kế thừa theo hướng ch&iacute;nh qui th&ocirc;ng qua c&aacute;c lớp học ngắn hạn, d&agrave;i hạn; c&aacute;c lớp bồi dưỡng CB-CNV được tổ chức trong nước cũng như ở nước ngo&agrave;i đều được l&atilde;nh đạo FAHASA đặc biệt quan t&acirc;m v&agrave; tạo điều kiện triển khai thực hiện. Ch&iacute;nh v&igrave; thế, tr&igrave;nh độ chuy&ecirc;n m&ocirc;n của đội ngũ CB-CNV ng&agrave;y c&agrave;ng được n&acirc;ng cao, đ&aacute;p ứng nhu cầu ng&agrave;y c&agrave;ng tăng của c&ocirc;ng việc cũng như sự ph&aacute;t triển của x&atilde; hội đang tr&ecirc;n đường hội nhập.<strong></strong></p>
<p style="text-align: justify;"><strong>Về h&agrave;ng h&oacute;a </strong></p>
<p style="text-align: justify;">C&ocirc;ng ty FAHASA chuy&ecirc;n kinh doanh: s&aacute;ch quốc văn, ngoại văn, văn h&oacute;a phẩm, văn ph&ograve;ng phẩm, dụng cụ học tập, qu&agrave; lưu niệm, đồ chơi d&agrave;nh cho trẻ em&hellip; Một số Nh&agrave; s&aacute;ch trực thuộc C&ocirc;ng ty FAHASA c&ograve;n kinh doanh c&aacute;c mặt h&agrave;ng si&ecirc;u thị như: h&agrave;ng ti&ecirc;u d&ugrave;ng, h&agrave;ng gia dụng, h&oacute;a&nbsp; mỹ phẩm&hellip;</p>
<p style="text-align: justify;">S&aacute;ch quốc văn với nhiều thể loại đa dạng như s&aacute;ch gi&aacute;o khoa &ndash; tham khảo, gi&aacute;o tr&igrave;nh, s&aacute;ch học ngữ, từ điển, s&aacute;ch tham khảo thuộc nhiều chuy&ecirc;n ng&agrave;nh phong ph&uacute;: văn học, t&acirc;m l&yacute; &ndash; gi&aacute;o dục, khoa học kỹ thuật, khoa học kinh tế - x&atilde; hội, khoa học thường thức, s&aacute;ch phong thủy, nghệ thuật sống, danh ng&ocirc;n, s&aacute;ch thiếu nhi, truyện tranh, truyện đọc, từ điển, c&ocirc;ng nghệ th&ocirc;ng tin, khoa học &ndash; kỹ thuật, nấu ăn, l&agrave;m đẹp...&nbsp; của nhiều Nh&agrave; xuất bản, nh&agrave; cung cấp s&aacute;ch c&oacute; uy t&iacute;n như: NXB Trẻ, Gi&aacute;o Dục, Kim Đồng, Văn h&oacute;a -Văn Nghệ, Tổng hợp TP.HCM, Ch&iacute;nh Trị Quốc Gia; C&ocirc;ng ty Đ&ocirc;ng A, Nh&atilde; Nam, B&aacute;ch Việt, Alphabook, Th&aacute;i H&agrave;, Minh L&acirc;m, Đinh Tị, Minh Long, TGM, S&aacute;ng Tạo Tr&iacute; Việt, Khang Việt, To&agrave;n Ph&uacute;c&hellip;</p>
<p style="text-align: justify;">S&aacute;ch ngoại văn bao gồm: từ điển, gi&aacute;o tr&igrave;nh, tham khảo, truyện tranh thiếu nhi , s&aacute;ch học ngữ, từ vựng, ngữ ph&aacute;p, luyện thi TOEFL, TOEIC, IELS&hellip;được nhập từ c&aacute;c NXB nước ngo&agrave;i như<em>: </em>Cambridge, Mc Graw-Hill, Pearson Education, Oxford, Macmillan, Cengage Learning&hellip;</p>
<p style="text-align: justify;">Văn ph&ograve;ng phẩm, dụng cụ học tập, đồ chơi d&agrave;nh cho trẻ em, h&agrave;ng lưu niệm&hellip; đa dạng, phong ph&uacute;, mẫu m&atilde; đẹp, chất lượng tốt, được cung ứng bởi c&aacute;c c&ocirc;ng ty, nh&agrave; cung cấp uy t&iacute;n như: Thi&ecirc;n Long, XNK B&igrave;nh T&acirc;y, Hạnh Thuận, Ng&ocirc; Quang, Việt Văn, Trương Vui, Hương Mi, Phương Nga, Việt Tinh Anh, Chăm s&oacute;c trẻ em Việt, Mẹ v&agrave; em b&eacute;&hellip;</p>
<p style="text-align: justify;">C&ugrave;ng với việc ph&aacute;t h&agrave;nh độc quyền nhiều ấn bản c&aacute;c loại của c&aacute;c Nh&agrave; xuất bản l&agrave; năng lực in ấn, sản xuất cung ứng nguồn h&agrave;ng của X&iacute; nghiệp in FAHASA, đ&atilde; gi&uacute;p C&ocirc;ng ty lu&ocirc;n chủ động được nguồn h&agrave;ng, nhất l&agrave; c&aacute;c mặt h&agrave;ng độc quyền như: lịch bloc, tập học sinh, sổ tay cao cấp, agenda, văn ph&ograve;ng phẩm, dụng cụ học tập&hellip;<strong></strong></p>
<p style="text-align: justify;"><strong></strong><strong>Hệ thống Nh&agrave; s&aacute;ch chuy&ecirc;n nghiệp</strong></p>
<p style="text-align: justify;">Mạng lưới ph&aacute;t h&agrave;nh của C&ocirc;ng ty FAHASA rộng khắp tr&ecirc;n to&agrave;n quốc, gồm 5 Trung t&acirc;m s&aacute;ch, 1 X&iacute; nghiệp in v&agrave; với gần 60 Nh&agrave; s&aacute;ch trải dọc khắp c&aacute;c tỉnh th&agrave;nh từ TP.HCM đến Thủ Đ&ocirc; H&agrave; Nội, miền Trung, T&acirc;y Nguy&ecirc;n, miền Đ&ocirc;ng v&agrave; T&acirc;y Nam Bộ như: H&agrave; Nội, Vĩnh Ph&uacute;c, Hải Ph&ograve;ng, Thanh H&oacute;a, H&agrave; Tĩnh, Huế, Đ&agrave; Nẵng, Quảng Nam, Quảng Ng&atilde;i, Quy Nhơn, Nha Trang, Gia Lai, Đăklăk, Bảo Lộc - L&acirc;m Đồng, Ninh Thuận, B&igrave;nh Thuận, B&igrave;nh Phước, B&igrave;nh Dương, Đồng Nai, Vũng T&agrave;u, Long An, Tiền Giang, Bến Tre, Vĩnh Long, Cần Thơ, Hậu Giang, An Giang, Ki&ecirc;n Giang, S&oacute;c Trăng, C&agrave; Mau.</p>
<p style="text-align: justify;">Năm 2004 C&ocirc;ng ty đ&atilde; được Cục Sở hữu Tr&iacute; tuệ Việt Nam c&ocirc;ng nhận sở hữu độc quyền t&ecirc;n thương hiệu FAHASA.</p>
<p style="text-align: justify;">Năm 2005, C&ocirc;ng ty FAHASA được Trung t&acirc;m s&aacute;ch kỷ lục Việt Nam c&ocirc;ng nhận l&agrave; đơn vị c&oacute; hệ thống Nh&agrave; s&aacute;ch nhiều nhất Việt Nam; được Tạp ch&iacute; The Guide c&ocirc;ng nhận Nh&agrave; s&aacute;ch Xu&acirc;n Thu - đơn vị trực thuộc C&ocirc;ng ty FAHASA l&agrave; Nh&agrave; s&aacute;ch Ngoại văn đẹp nhất, lớn nhất, quy m&ocirc; nhất, nhiều s&aacute;ch nhất ở Th&agrave;nh phố Hồ Ch&iacute; Minh v&agrave; cả nước.</p>
<p style="text-align: justify;">Năm 2012 FAHASA l&agrave; Doanh nghiệp nằm trong Top 10 nh&agrave; b&aacute;n lẻ h&agrave;ng đầu Việt Nam. Đặc biệt năm 2006, 2009, 2012 FAHASA đạt danh hiệu Top 500 Nh&agrave; b&aacute;n lẻ h&agrave;ng đầu Ch&acirc;u &Aacute; Th&aacute;i B&igrave;nh Dương, giải thưởng được tạp ch&iacute; Retail Asia (Singapore) b&igrave;nh chọn.<strong></strong></p>
<p style="text-align: justify;"><strong>Kinh nghiệm hoạt động </strong></p>
<p style="text-align: justify;">L&agrave; đơn vị c&oacute; gần 40 năm kinh doanh v&agrave; phục vụ x&atilde; hội, n&ecirc;n FAHASA đ&atilde; t&iacute;ch lũy được nhiều kinh nghiệm trong việc nghi&ecirc;n cứu thị trường, ph&acirc;n t&iacute;ch t&agrave;i ch&iacute;nh, định hướng ph&aacute;t triển, hoạch định chiến lược kinh doanh v&agrave; khả năng tiếp thị giỏi&hellip; Đồng thời FAHASA c&ograve;n c&oacute; nhiều kinh nghiệm trong việc tổ chức c&aacute;c cuộc Hội thảo, Triển l&atilde;m v&agrave; giới thiệu s&aacute;ch quốc văn, ngoại văn với qui m&ocirc; lớn, ấn tượng.</p>
<p style="text-align: justify;">FAHASA lu&ocirc;n l&agrave; đơn vị đi ti&ecirc;n phong trong nhiều hoạt động x&atilde; hội, điển h&igrave;nh l&agrave; việc tham gia tổ chức c&aacute;c Hội s&aacute;ch ở TP.HCM như: Hội s&aacute;ch Th&agrave;nh Phố Hồ Ch&iacute; Minh, Hội s&aacute;ch Thiếu nhi ngoại th&agrave;nh, Hội s&aacute;ch M&ugrave;a khai trường, Hội s&aacute;ch Học đường, Hội s&aacute;ch Trường Quốc tế&hellip; Nổi bật nhất l&agrave; Hội s&aacute;ch Th&agrave;nh Phố Hồ Ch&iacute; Minh, được định kỳ tổ chức 2 năm một lần. Đ&acirc;y l&agrave; Hội s&aacute;ch c&oacute; qui m&ocirc; lớn, tầm ảnh hưởng rộng, đ&atilde; để lại &yacute; nghĩa kinh tế, văn h&oacute;a v&agrave; x&atilde; hội s&acirc;u sắc. Hội s&aacute;ch kh&ocirc;ng chỉ l&agrave; nơi hội tụ văn h&oacute;a l&yacute; tưởng đối với người d&acirc;n TP.HCM 
    m&agrave; c&ograve;n l&agrave; một th&ocirc;ng điệp văn h&oacute;a t&ocirc;n vinh cho c&aacute;c hoạt động Xuất bản &ndash; Ph&aacute;t h&agrave;nh s&aacute;ch cả nước, n&acirc;ng tầm cho việc giao lưu, trao đổi văn h&oacute;a với bạn b&egrave; thế giới, đồng thời g&oacute;p phần đem s&aacute;ch - tri thức đến gần hơn với mọi tầng lớp nh&acirc;n d&acirc;n, phục vụ tốt hơn nhu cầu văn h&oacute;a tinh thần của x&atilde; hội</p>

                    </div>
</section>
<?php
include_once 'site/view/pages/v_left.php';